/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.gui;

import cliente.objetosremotos.JefeDepartamentoRemoto;
import cliente.utilidades.Constantes;
import cliente.utilidades.Mensajes;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import servidor.dto.ObjetosDTO.AnteproyectoCompletoDTO;
import servidor.dto.ObjetosDTO.NodoAnteproyectoDTO;

/**
 *
 * @author andres
 */
public class JefeDepartamentoGUI extends javax.swing.JFrame {

    private String direcionIP;
    private int puerto;
    private JefeDepartamentoRemoto servicioJefeD;

    /**
     * Creates new form JefeDGUI
     */
    public JefeDepartamentoGUI(String dirIP, int puerto) throws RemoteException {
        this.direcionIP = dirIP;
        this.puerto = puerto;
        this.servicioJefeD = new JefeDepartamentoRemoto(this, this.direcionIP, this.puerto);
        if (this.servicioJefeD.iniciar()) {
            initComponents();
            limpiarRegistroUsuario();
            limpiarRegistrarAnteproyecto();
            limpiarBuscarAnteproyecto();
            limpiarAsignarAnteproyecto();
            generarCodigo();
        } else {
            Mensajes.error(this, "ERROR AL UBICAR EL OBJETO REMOTO");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomApeRU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdentificacionRU = new javax.swing.JTextField();
        txtUsuarioUnicaucaisRU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtContraseniaRU = new javax.swing.JTextField();
        btnRegistrarRU = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbModalidadRA = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTituloRA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoRA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstudiante1RA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEstudiante2RA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDirectorRA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCoDirectorRA = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNumRevisionRA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFechaRA = new javax.swing.JFormattedTextField();
        btnRegistroAntep = new javax.swing.JButton();
        txtFechaAprobRA = new javax.swing.JFormattedTextField();
        cbConceptoRA = new javax.swing.JComboBox<>();
        cbEstadoRA = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoAntAE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNomEval1AE = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbConcEval1AE = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtFecRevEval1AE = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNomEval2AE = new javax.swing.JTextField();
        cbConcEval2AE = new javax.swing.JComboBox<>();
        txtFecRevEval2AE = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnAsignarEvaluadores = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtCodigoAntBA = new javax.swing.JTextField();
        btnBuscarBA = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtEstadoBA = new javax.swing.JTextField();
        txtConceptoBA = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtModaliadaBA = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtFechaAprBA = new javax.swing.JTextField();
        txtTituloBA = new javax.swing.JTextField();
        txtFechaRegBA = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCoDirectorBA = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtCodigoBA = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtDirectorBA = new javax.swing.JTextField();
        txtEstudiante2BA = new javax.swing.JTextField();
        txtEstudiante1BA = new javax.swing.JTextField();
        txtNumRevisionBA = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAnteproyectosLA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JEFE DE DEPARTAMENTO");
        setMaximumSize(new java.awt.Dimension(1020, 510));
        setPreferredSize(new java.awt.Dimension(1020, 510));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 420));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 420));

        jLabel1.setText("MENU JEFE DE DEPARTAMENTO");

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(900, 450));

        jLabel2.setText("NOMBRES Y APELLIDOS");

        txtNomApeRU.setText("TETERTETRE");
        txtNomApeRU.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel3.setText("IDENTIFICAIÓN");

        txtIdentificacionRU.setText("ERTERT");

        txtUsuarioUnicaucaisRU.setText("ERTERT");

        jLabel4.setText("USUARIO UNICAUCA");

        jLabel5.setText("CONTRASEÑA");

        txtContraseniaRU.setText("ERTERTER");

        btnRegistrarRU.setText("REGISTRAR USUARIO");
        btnRegistrarRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRUActionPerformed(evt);
            }
        });

        jLabel39.setText("TIPO DE USUARIO");

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jede Departamento", "Estudiante - Director", "Evaluadoor" }));
        cbTipoUsuario.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomApeRU, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(txtUsuarioUnicaucaisRU)
                            .addComponent(txtIdentificacionRU, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(txtContraseniaRU)
                            .addComponent(cbTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnRegistrarRU)))
                .addGap(0, 281, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomApeRU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacionRU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioUnicaucaisRU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseniaRU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarRU)
                .addGap(162, 162, 162))
        );

        jTabbedPane2.addTab("REG. USUARIOS", jPanel2);

        jPanel3.setAutoscrolls(true);
        jPanel3.setPreferredSize(new java.awt.Dimension(980, 480));

        jLabel6.setText("MODALIDAD");

        cbModalidadRA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajo de Investigación(TI)", "Práctica Profesional(PP)." }));

        jLabel7.setText("TITULO");

        txtTituloRA.setText("titulo");
        txtTituloRA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtTituloRA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel8.setText("CÓDIGO ANNTE.");

        txtCodigoRA.setEditable(false);
        txtCodigoRA.setText("codigo");
        txtCodigoRA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtCodigoRA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel10.setText("NOM. ESTUDIANTE 1");

        txtEstudiante1RA.setText("codigo");
        txtEstudiante1RA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtEstudiante1RA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel11.setText("NOM. ESTUDIANTE 2");

        txtEstudiante2RA.setText("codigo");
        txtEstudiante2RA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtEstudiante2RA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel12.setText("NOM. DIRECTOR");

        txtDirectorRA.setText("codigo");
        txtDirectorRA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtDirectorRA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel13.setText("NOM. CO-DIRECTOR");

        txtCoDirectorRA.setText("codigo");
        txtCoDirectorRA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtCoDirectorRA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel14.setText("FECHA APROBACION");

        jLabel15.setText("CONCEPTO");

        jLabel16.setText("ESTADO");

        jLabel17.setText("NUM. REVISIÓN");

        txtNumRevisionRA.setText("codigo");
        txtNumRevisionRA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtNumRevisionRA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel18.setText("FECHA REGISTRO");

        txtFechaRA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFechaRA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaRA.setPreferredSize(new java.awt.Dimension(40, 40));

        btnRegistroAntep.setText("REGISTRAR");
        btnRegistroAntep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAntepActionPerformed(evt);
            }
        });

        txtFechaAprobRA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFechaAprobRA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaAprobRA.setPreferredSize(new java.awt.Dimension(40, 40));

        cbConceptoRA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Aprobado", "Aprobado" }));

        cbEstadoRA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Asignación", "Evaluadores Asignados", "En revisión", "Evaluado" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEstudiante1RA, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(txtTituloRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtEstudiante2RA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDirectorRA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbModalidadRA, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumRevisionRA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbEstadoRA, javax.swing.GroupLayout.Alignment.LEADING, 0, 359, Short.MAX_VALUE)
                                    .addComponent(cbConceptoRA, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFechaAprobRA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCoDirectorRA, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                    .addComponent(txtFechaRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroAntep, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371)))
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbModalidadRA)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(txtCoDirectorRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18)
                    .addComponent(txtFechaRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(txtFechaAprobRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstudiante1RA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(cbConceptoRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstudiante2RA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirectorRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(txtNumRevisionRA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistroAntep)
                .addGap(317, 317, 317))
        );

        jTabbedPane2.addTab("REG. ANTEPROYECTOS", jPanel3);

        jLabel9.setText("CÓDIGO ANTEPROYECTO");

        txtCodigoAntAE.setText("codigo");

        jLabel19.setText("NOM. EVALUADOR 1");

        txtNomEval1AE.setText("jTextField1");

        jLabel20.setText("CONCEPTO EVAL. 1");

        cbConcEval1AE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Aprobado", "Aprobado" }));

        jLabel21.setText("FECHA REVISIÓN");

        txtFecRevEval1AE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel22.setText("NOM. EVALUADOR 2");

        jLabel23.setText("CONCEPTO EVAL. 2");

        jLabel24.setText("FECHA REVISIÓN");

        txtNomEval2AE.setText("jTextField1");

        cbConcEval2AE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Aprobado", "Aprobado" }));

        txtFecRevEval2AE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAsignarEvaluadores.setText("ASIGNAR");
        btnAsignarEvaluadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarEvaluadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoAntAE, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomEval1AE, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(20, 20, 20)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbConcEval1AE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFecRevEval1AE, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomEval2AE, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(13, 13, 13)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbConcEval2AE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFecRevEval2AE, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnAsignarEvaluadores, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodigoAntAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtNomEval1AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtNomEval2AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(cbConcEval1AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(cbConcEval2AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtFecRevEval1AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(txtFecRevEval2AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignarEvaluadores)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ASIGNAR EVALUADORES", jPanel4);

        jLabel25.setText("CÓDIGO ANTEPROYECTO");

        txtCodigoAntBA.setText("codigo");

        btnBuscarBA.setText("BUSCAR");
        btnBuscarBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBAActionPerformed(evt);
            }
        });

        jPanel7.setEnabled(false);

        txtEstadoBA.setText("codigo");
        txtEstadoBA.setEnabled(false);
        txtEstadoBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtEstadoBA.setPreferredSize(new java.awt.Dimension(40, 40));

        txtConceptoBA.setText("codigo");
        txtConceptoBA.setEnabled(false);
        txtConceptoBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtConceptoBA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel26.setText("MODALIDAD");

        txtModaliadaBA.setText("codigo");
        txtModaliadaBA.setEnabled(false);
        txtModaliadaBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtModaliadaBA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel27.setText("TITULO");

        txtFechaAprBA.setText("codigo");
        txtFechaAprBA.setEnabled(false);
        txtFechaAprBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtFechaAprBA.setPreferredSize(new java.awt.Dimension(40, 40));

        txtTituloBA.setText("titulo");
        txtTituloBA.setEnabled(false);
        txtTituloBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtTituloBA.setPreferredSize(new java.awt.Dimension(40, 40));

        txtFechaRegBA.setText("codigo");
        txtFechaRegBA.setEnabled(false);
        txtFechaRegBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtFechaRegBA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel28.setText("NOM. CO-DIRECTOR");

        txtCoDirectorBA.setText("codigo");
        txtCoDirectorBA.setEnabled(false);
        txtCoDirectorBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtCoDirectorBA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel29.setText("FECHA REGISTRO");

        jLabel30.setText("FECHA APROBACION");

        txtCodigoBA.setText("codigo");
        txtCodigoBA.setEnabled(false);
        txtCodigoBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtCodigoBA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel31.setText("CÓDIGO ANTE.");

        jLabel32.setText("NOM. ESTUDIANTE 1");

        jLabel33.setText("NOM. ESTUDIANTE 2");

        jLabel34.setText("NOM. DIRECTOR");

        txtDirectorBA.setText("codigo");
        txtDirectorBA.setEnabled(false);
        txtDirectorBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtDirectorBA.setPreferredSize(new java.awt.Dimension(40, 40));

        txtEstudiante2BA.setText("codigo");
        txtEstudiante2BA.setEnabled(false);
        txtEstudiante2BA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtEstudiante2BA.setPreferredSize(new java.awt.Dimension(40, 40));

        txtEstudiante1BA.setText("codigo");
        txtEstudiante1BA.setEnabled(false);
        txtEstudiante1BA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtEstudiante1BA.setPreferredSize(new java.awt.Dimension(40, 40));

        txtNumRevisionBA.setText("codigo");
        txtNumRevisionBA.setEnabled(false);
        txtNumRevisionBA.setMinimumSize(new java.awt.Dimension(20, 41));
        txtNumRevisionBA.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel35.setText("NUM. REVISIÓN");

        jLabel36.setText("ESTADO");

        jLabel37.setText("CONCEPTO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTituloBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEstudiante2BA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDirectorBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEstudiante1BA, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoBA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtModaliadaBA, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCoDirectorBA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFechaRegBA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFechaAprBA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConceptoBA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoBA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumRevisionBA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(txtModaliadaBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(txtTituloBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(txtFechaAprBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstudiante1BA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel37)
                            .addComponent(txtConceptoBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstudiante2BA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(txtEstadoBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirectorBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumRevisionBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCoDirectorBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaRegBA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoAntBA, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscarBA, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtCodigoAntBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBA))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("BUSCAR ANTEŔOYECTO", jPanel5);

        jLabel38.setText("LISTA DE ANTEPROYECTOS REGISTRADOS");

        tbAnteproyectosLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "CÓDIGO", "TITULO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAnteproyectosLA);
        if (tbAnteproyectosLA.getColumnModel().getColumnCount() > 0) {
            tbAnteproyectosLA.getColumnModel().getColumn(0).setMinWidth(80);
            tbAnteproyectosLA.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel38))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("LISTAR ANTEPROYECTOS", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRUActionPerformed
        if (txtUsuarioUnicaucaisRU.getText().equals("")
                || txtNomApeRU.getText().equals("")
                || txtContraseniaRU.getText().equals("")
                || txtIdentificacionRU.getText().equals("")) {
            Mensajes.error(jPanel1, "Debe ingresar todos los datos!");
        } else {
            try {
                this.servicioJefeD.registrarUsuario(txtNomApeRU.getText(), Integer.parseInt(txtIdentificacionRU.getText()), txtUsuarioUnicaucaisRU.getText(), txtContraseniaRU.getText(), cbTipoUsuario.getSelectedIndex() + 1);
                limpiarRegistroUsuario();

            } catch (RemoteException ex) {
                Mensajes.error(jPanel1, "No se pudo realizar la conexion con el servidor!");
                Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRegistrarRUActionPerformed

    private void btnRegistroAntepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAntepActionPerformed
        String modalidad = cbModalidadRA.getSelectedItem().toString();
        String titulo = txtTituloRA.getText();
        String codigo = txtCodigoRA.getText();
        String e1 = txtEstudiante1RA.getText();
        String e2 = txtEstudiante2RA.getText();
        String director = txtDirectorRA.getText();
        String coDirector = txtCoDirectorRA.getText();
        String fechaR = txtFechaRA.getText();
        String fechaAp = txtFechaAprobRA.getText();
        int concepto = cbConceptoRA.getSelectedIndex() + 1;
        int estado = cbEstadoRA.getSelectedIndex() + 1;
        String numeroRev = txtNumRevisionRA.getText();

        if (titulo.equals("") || codigo.equals("") || e1.equals("") || e2.equals("")
                || director.equals("") || coDirector.equals("") || fechaR.equals("") || fechaAp.equals("")
                || numeroRev.equals("")) {
            Mensajes.error(jPanel1, "Debe ingresar todos los valores!");
        } else {
            try {
                this.servicioJefeD.registrarAnteproyecto(modalidad, titulo, codigo, e1, e2, director, coDirector, fechaR, fechaAp, concepto, estado, Integer.parseInt(numeroRev));
                limpiarRegistrarAnteproyecto();
            } catch (RemoteException ex) {
                Mensajes.error(jPanel1, "No se pudo realizar la conexion con el servidor!");
                Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException nfe) {
                Mensajes.error(jPanel1, "El número de revision debe ser un numero!");
            }
        }
    }//GEN-LAST:event_btnRegistroAntepActionPerformed

    private void btnAsignarEvaluadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarEvaluadoresActionPerformed
        String codigo = txtCodigoAntAE.getText();
        String nomEva1 = txtNomEval1AE.getText();
        String nomEva2 = txtNomEval2AE.getText();
        String fechaEva1 = txtFecRevEval1AE.getText();
        String fechaEva2 = txtFecRevEval2AE.getText();
        String conceptoEva1 = cbConcEval1AE.getSelectedItem().toString();
        String conceptoEva2 = cbConcEval2AE.getSelectedItem().toString();

        if (codigo.equals("") || nomEva1.equals("") || nomEva2.equals("")
                || fechaEva1.equals("") || fechaEva2.equals("")) {
            Mensajes.error(jPanel1, "Debe ingresar todos los valores!");

        } else {

        }

    }//GEN-LAST:event_btnAsignarEvaluadoresActionPerformed

    private void btnBuscarBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBAActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoAntBA.getText();
        if (codigo.equals("")) {
            Mensajes.error(jPanel1, "Debe ingresar el código!");
        } else {
            try {
                this.servicioJefeD.buscarAnteproyecto(codigo);
            } catch (RemoteException ex) {
                Mensajes.error(jPanel1, "No se pudo realizar la conexion con el servidor!");
                Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarBAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JefeDepartamentoGUI("localhost", 1099).setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(JefeDepartamentoGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void cargarAnteproyecto(AnteproyectoCompletoDTO anteproyectoCompletoDTO) {
        txtModaliadaBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getModalidad());
        txtTituloBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getTitulo());
        txtCodigoBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getCodigo());
        txtEstudiante1BA.setText(anteproyectoCompletoDTO.getAnteproyecto().getNombreEstudiante1());
        txtEstudiante2BA.setText(anteproyectoCompletoDTO.getAnteproyecto().getNombreEstudiante2());
        txtDirectorBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getNombreDirector());
        txtCoDirectorBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getNombreCoDirector());
        txtFechaRegBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getFechaRegistro());
        txtFechaAprBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getFechaAprobacion());
        txtConceptoBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getConcepto() + "");
        txtEstadoBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getEstado() + "");
        txtNumRevisionBA.setText(anteproyectoCompletoDTO.getAnteproyecto().getNumeroRevision() + "");
    }

    public void limpiarRegistroUsuario() {
        txtUsuarioUnicaucaisRU.setText("");
        txtIdentificacionRU.setText("");
        txtNomApeRU.setText("");
        txtContraseniaRU.setText("");
        cbTipoUsuario.setSelectedIndex(1);
    }

    public void limpiarAsignarAnteproyecto() {
        txtCodigoAntAE.setText("");
        txtNomEval1AE.setText("");
        txtNomEval2AE.setText("");
        txtFecRevEval1AE.setText("");
        txtFecRevEval2AE.setText("");
        cbConcEval1AE.setSelectedIndex(0);
        cbConcEval2AE.setSelectedIndex(0);

    }

    public void limpiarRegistrarAnteproyecto() {
        cbModalidadRA.setSelectedIndex(0);
        txtTituloRA.setText("");
        txtCodigoRA.setText("");
        txtEstudiante1RA.setText("");
        txtEstudiante2RA.setText("");
        txtDirectorRA.setText("");
        txtCoDirectorRA.setText("");
        txtFechaRA.setText("");
        txtFechaAprobRA.setText("");
        cbConceptoRA.setSelectedIndex(0);
        cbEstadoRA.setSelectedIndex(0);
        txtNumRevisionRA.setText("");
    }

    public void limpiarBuscarAnteproyecto() {
        txtCodigoAntBA.setText("");
        txtModaliadaBA.setText("");
        txtTituloBA.setText("");
        txtCodigoBA.setText("");
        txtEstudiante1BA.setText("");
        txtEstudiante2BA.setText("");
        txtDirectorBA.setText("");
        txtCoDirectorBA.setText("");
        txtFechaRegBA.setText("");
        txtFechaAprBA.setText("");
        txtConceptoBA.setText("");
        txtEstadoBA.setText("");
        txtNumRevisionBA.setText("");
    }

    public void cargarBuscarAnteproyecto(NodoAnteproyectoDTO nadto) {

        txtModaliadaBA.setText(nadto.getModalidad());
        txtTituloBA.setText(nadto.getTitulo());
        txtCodigoBA.setText(nadto.getCodigo());
        txtEstudiante1BA.setText(nadto.getNombreEstudiante1());
        txtEstudiante2BA.setText(nadto.getNombreEstudiante2());
        txtDirectorBA.setText(nadto.getNombreDirector());
        txtCoDirectorBA.setText(nadto.getNombreCoDirector());
        txtFechaRegBA.setText(nadto.getFechaRegistro());
        txtFechaAprBA.setText(nadto.getFechaAprobacion());
        txtConceptoBA.setText(Constantes.Concepto[nadto.getConcepto()]);
        txtEstadoBA.setText(Constantes.Estado[nadto.getEstado()]);
        txtNumRevisionBA.setText(nadto.getNumeroRevision() + "");
    }

    private void generarCodigo() {
        long number = (long) Math.floor(Math.random() * 9_000_000_000L) + 1_000_000_000L;
        txtCodigoRA.setText(number + "");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarEvaluadores;
    private javax.swing.JButton btnBuscarBA;
    private javax.swing.JButton btnRegistrarRU;
    private javax.swing.JButton btnRegistroAntep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbConcEval1AE;
    private javax.swing.JComboBox<String> cbConcEval2AE;
    private javax.swing.JComboBox<String> cbConceptoRA;
    private javax.swing.JComboBox<String> cbEstadoRA;
    private javax.swing.JComboBox<String> cbModalidadRA;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbAnteproyectosLA;
    private javax.swing.JTextField txtCoDirectorBA;
    private javax.swing.JTextField txtCoDirectorRA;
    private javax.swing.JTextField txtCodigoAntAE;
    private javax.swing.JTextField txtCodigoAntBA;
    private javax.swing.JTextField txtCodigoBA;
    private javax.swing.JTextField txtCodigoRA;
    private javax.swing.JTextField txtConceptoBA;
    private javax.swing.JTextField txtContraseniaRU;
    private javax.swing.JTextField txtDirectorBA;
    private javax.swing.JTextField txtDirectorRA;
    private javax.swing.JTextField txtEstadoBA;
    private javax.swing.JTextField txtEstudiante1BA;
    private javax.swing.JTextField txtEstudiante1RA;
    private javax.swing.JTextField txtEstudiante2BA;
    private javax.swing.JTextField txtEstudiante2RA;
    private javax.swing.JFormattedTextField txtFecRevEval1AE;
    private javax.swing.JFormattedTextField txtFecRevEval2AE;
    private javax.swing.JTextField txtFechaAprBA;
    private javax.swing.JFormattedTextField txtFechaAprobRA;
    private javax.swing.JFormattedTextField txtFechaRA;
    private javax.swing.JTextField txtFechaRegBA;
    private javax.swing.JTextField txtIdentificacionRU;
    private javax.swing.JTextField txtModaliadaBA;
    private javax.swing.JTextField txtNomApeRU;
    private javax.swing.JTextField txtNomEval1AE;
    private javax.swing.JTextField txtNomEval2AE;
    private javax.swing.JTextField txtNumRevisionBA;
    private javax.swing.JTextField txtNumRevisionRA;
    private javax.swing.JTextField txtTituloBA;
    private javax.swing.JTextField txtTituloRA;
    private javax.swing.JTextField txtUsuarioUnicaucaisRU;
    // End of variables declaration//GEN-END:variables

}
